# =========================
# This file is used to containerize the React web application for CI/CD pipeline deployment on Google Cloud Run via Cloud Build.
# It uses a multi-stage build to first build the React app and then serve it using Nginx.
# =========================

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'northamerica-northeast1-docker.pkg.dev/merci-509500/pjb-arti-repo/prairiejoy-web:$COMMIT_SHA'
      - '.'

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'northamerica-northeast1-docker.pkg.dev/merci-509500/pjb-arti-repo/prairiejoy-web:$COMMIT_SHA'

  # 3. Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'prairiejoy-web'
      - '--image'
      - 'northamerica-northeast1-docker.pkg.dev/merci-509500/pjb-arti-repo/prairiejoy-web:$COMMIT_SHA'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'

images:
  - 'northamerica-northeast1-docker.pkg.dev/merci-509500/pjb-arti-repo/prairiejoy-web:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

# Bind the predifined Cloud Build service account to the Cloud Run Invoker role for the deployed service.
serviceAccount: 'projects/merci-509500/serviceAccounts/cloud-build-sa@merci-509500.iam.gserviceaccount.com'
